env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  brace-style:
    - error
    - allman
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  no-trailing-spaces:
    - error
  no-unused-vars:
    - error
    - varsIgnorePattern: _
      argsIgnorePattern: _
  quotes:
    - error
    - double
    - avoidEscape: true
  semi:
    - error
    - never
